package dojo.f.dev.com.appdojo.utils;

/**
 * Created by Administrador on 08/08/17.
 */

public class Constants {


    public static final String PREFERENCES_DEVF = "preferences_dev";
    public static final String PREFERENCES_DEVF_KEY_PASS = "pass";
    public static final String PREFERENCES_DEFF_KEY_USER = "user";
    public static final String PREFERENCES_DEVF_KEY_TOKEN = "token";
    public static final String URL_BASE_DOJO = "https://us-central1-devf-dojo-admin.cloudfunctions.net/";
    public static final String JSON_WEB_TOKEN = "Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6ImI1ZmEwNmQ5YWFhODg4MjA0YzdiOTBkMjQ2NTU1ZWNlOTFlZDQxMTcifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vZGV2Zi1kb2pvLWFkbWluIiwibmFtZSI6IkVybmVzdG8gUmFtaXJleiIsInBpY3R1cmUiOiJodHRwczovL2F2YXRhcnMxLmdpdGh1YnVzZXJjb250ZW50LmNvbS91LzMyMzYzOTg_dj00IiwiYXVkIjoiZGV2Zi1kb2pvLWFkbWluIiwiYXV0aF90aW1lIjoxNTAyMzMyMzA2LCJ1c2VyX2lkIjoiek9kbEJZYTdEbWZlelNCbzhUUGp6MDJzWkg4MyIsInN1YiI6InpPZGxCWWE3RG1mZXpTQm84VFBqejAyc1pIODMiLCJpYXQiOjE1MDIzMzIzMDYsImV4cCI6MTUwMjMzNTkwNiwiZW1haWwiOiJuZWFydG94QG91dGxvb2suY29tIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7ImdpdGh1Yi5jb20iOlsiMzIzNjM5OCJdLCJlbWFpbCI6WyJuZWFydG94QG91dGxvb2suY29tIl19LCJzaWduX2luX3Byb3ZpZGVyIjoiZ2l0aHViLmNvbSJ9fQ.cxgbSQclj1F9r5lnZkLVmx_fWJwr4FzB_G5z2Efyoyg10HRW_uSYYqdcMzWohMDsPIaCYqP2Hnp3zQS_yYbg4UUonVNOvcDCzH3vs-x25w2zOVFIuZ2kGowWg_BImSr59iujXHbAqSgJHDkTENjrmy57wm4UZsWX6oVBXCixZil2El6hk1zspYSwgUzM7sguARqk8Hy2ERmy7KFfqCXFVRlx6wIHA7zgNVNBbjp3I6Bzl0TaxvWnkVT0l4_UUeXIQNagz9MnCfKNDa4YPij5TxmsPYbAN4aPFH2SmQrKGmetSF0KYRkQ4XcN4DofQWojIFo2h9k8r_lgHe98ALXCkA";

}
